### ISSUE TITLE
[META] Renaming Components

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#325]
### Top Level Issue for all issues related to renaming components

This will result into breaking changes. Once we have these complete, we will engage with thorough testing and release this in 2.0.0
RFC: https://github.com/opensearch-project/opensearch-benchmark/issues/324
- [x] Issue [execute-test, test_executions](https://github.com/opensearch-project/opensearch-benchmark/issues/307)
- [ ] Issue [test_procedures](https://github.com/opensearch-project/opensearch-benchmark/issues/308) -> Not doing
- [x] Issue [provision_configs, provision_config_instances](https://github.com/opensearch-project/opensearch-benchmark/issues/310) PR #400 
- [x] Issue [results_publishing](https://github.com/opensearch-project/opensearch-benchmark/issues/311) and associated PR  #316
- [x] Issue [load_worker_coordinator_hosts, node-ip, coordinator-ip, (distributed workload generation)](https://github.com/opensearch-project/opensearch-benchmark/issues/258) PR #407

**Comment by IanHoang** [comment]
@beaioun found that there are still some iterations of provision-config-instsances in several places (like metrics.py). We will need to create a follow-up PR
