### ISSUE TITLE
[META] OSB 1.1.0 Prep List

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#351]
#### P0 Items
- [x] Add version branches 1.0 and 1.x
- [x] Revert results_publishing commit #316 #353 
- [x] Segment Replication #346 
- [x] Update datastore config to support number of shards and replicas for external datastore#336 
- [x] ZSTD and ZSTD_NO_DICT Support #335 #306 
- [x] Serverless implementations support for OSB #354 #355 
- [x] SigV4 Support #158

**Comment by bbarani** [comment]
Can we also add https://github.com/opensearch-project/opensearch-benchmark/pull/346 to the list?

**Comment by IanHoang** [comment]
Release was done a couple weeks ago.
