### ISSUE TITLE
OSB 1.2.0 Prep List

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#367]
Checklist for what needs to be addressed before OSB 1.2.0 release:

- [x] Refactor put-pipeline #366 
- [x] Add Search Pipeline Capability #364 
- [ ] Build OSB prior to release instead of on release #303
