### ISSUE TITLE
[META] Create-Workload Enhancements

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#616]
META issue for issues related to this RFC: https://github.com/opensearch-project/opensearch-benchmark/issues/395

Issues based off priorities from RFC:

- [ ] Rearchitect Create-Workload: https://github.com/opensearch-project/opensearch-benchmark/issues/587
- [ ] Add Support for Random Sampling of Documents
- [ ] Add Support for RetryController / RepairController
- [ ] Add Support for Python Concurrent Extraction
- [ ] Add Support for Other Language Corpus Extractors

**Comment by IanHoang** [comment]
Deprecating this as we have detailed initiatives for this in #760 and #759
